micronaut:
  security:
    intercept-url-map:
      - pattern: /api/chapters/*/comments/**
        access:
          - isAuthenticated()
      - pattern: /api/books
        access:
          - ADMIN
      - pattern: /api/**
        access:
          - isAnonymous()
      - pattern: /**
        access:
          - isAnonymous()