micronaut:
  security:
    intercept-url-map:
      - pattern: /api/login
        access:
          - isAnonymous()
      - pattern: /api/register
        access:
          - isAnonymous()
      - pattern: /api/resend
        access:
          - isAnonymous()
      - pattern: /api/payments/*/ipn
        access:
          - isAnonymous()
      - pattern: /api/payments/result
        access:
          - isAnonymous()
      - pattern: /api/verify
        access:
          - isAnonymous()
      - pattern: /api/refresh
        access:
          - isAnonymous()
      - pattern: /**
        access:
          - isAuthenticated()